# Generated by Django 5.1.3 on 2024-12-24 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_is_verified_alter_user_phone_number'),
        ('zodiac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='zodiac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zodiac.zodiac', verbose_name='Знак зодиака'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
