# Generated by Django 5.1.3 on 2024-12-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_sex_userinfo_gender_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Рост'),
        ),
    ]
