# Generated by Django 5.1.3 on 2024-12-27 22:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_userinfo_birth_place_alter_userinfo_birth_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='compatability_preferences',
            field=models.IntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
