FROM python:3.11.9-slim

WORKDIR /usr/src/date_me

RUN pip install --upgrade pip

ENV PYTHONUNBUFFERED=1

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "worker.py"]