# Generated by Django 5.1.3 on 2024-12-30 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время создания пары')),
                ('first_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs_as_first', to=settings.AUTH_USER_MODEL, verbose_name='Первый участник пары')),
                ('second_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs_as_second', to=settings.AUTH_USER_MODEL, verbose_name='Второй участник пары')),
            ],
        ),
    ]
