# Generated by Django 5.1.3 on 2025-01-02 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания диалога')),
                ('pair', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dialog', to='dialogs.pair', verbose_name='Пара')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=350, verbose_name='Тело сообщения')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время создания сообщения')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор сообщения')),
                ('dialog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='dialogs.dialog', verbose_name='Сообщение')),
            ],
        ),
    ]
