# Generated by Django 5.1.3 on 2024-12-24 09:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zodiac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compatability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_from', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=6, verbose_name='Пол (от)')),
                ('gender_to', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=6, verbose_name='Пол (к)')),
                ('compatability', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Уровень совместимости')),
                ('zodiac_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatability_from', to='zodiac.zodiac', verbose_name='Совместимость знака зодиака')),
                ('zodiac_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatability_to', to='zodiac.zodiac', verbose_name='К знаку зодиака')),
            ],
            options={
                'verbose_name': 'Совместимость',
                'verbose_name_plural': 'Совместимости',
                'unique_together': {('zodiac_from', 'gender_from', 'zodiac_to', 'gender_to')},
            },
        ),
    ]
