# Generated by Django 5.1.3 on 2024-12-24 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compatability', '0001_initial'),
        ('zodiac', '0003_alter_zodiac_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compatability',
            old_name='zodiac_from',
            new_name='zodiac_female',
        ),
        migrations.RenameField(
            model_name='compatability',
            old_name='zodiac_to',
            new_name='zodiac_male',
        ),
        migrations.AlterUniqueTogether(
            name='compatability',
            unique_together={('zodiac_female', 'zodiac_male')},
        ),
        migrations.RemoveField(
            model_name='compatability',
            name='gender_from',
        ),
        migrations.RemoveField(
            model_name='compatability',
            name='gender_to',
        ),
    ]
