# Generated by Django 5.1.3 on 2024-12-26 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compatability', '0002_rename_zodiac_from_compatability_zodiac_female_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Swipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.BooleanField(verbose_name='Значение свайпа')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время свайпа')),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to=settings.AUTH_USER_MODEL, verbose_name='Кандидат')),
                ('swiper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swiped_by', to=settings.AUTH_USER_MODEL, verbose_name='Свайпер')),
            ],
        ),
    ]
