# Generated by Django 5.1.3 on 2024-12-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zodiac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zodiac',
            name='gender',
            field=models.CharField(choices=[('male', 'мужчина'), ('female', 'женщина')], default='male', max_length=6, verbose_name='Пол'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Знак зодиака'),
        ),
    ]
