# Generated by Django 5.1.3 on 2024-12-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zodiac', '0002_zodiac_gender_alter_zodiac_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zodiac',
            name='gender',
            field=models.CharField(choices=[('male', 'мужчина'), ('female', 'женщина')], default='male', max_length=6, verbose_name='Пол'),
        ),
    ]
